# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only
# Copyright (c) 2021 - 2024 Gavin Henry <ghenry@sentrypeer.org>
#
#   _____            _              _____
#  / ____|          | |            |  __ \
# | (___   ___ _ __ | |_ _ __ _   _| |__) |__  ___ _ __
#  \___ \ / _ \ '_ \| __| '__| | | |  ___/ _ \/ _ \ '__|
#  ____) |  __/ | | | |_| |  | |_| | |  |  __/  __/ |
# |_____/ \___|_| |_|\__|_|   \__, |_|   \___|\___|_|
#                              __/ |
#                             |___/
#
version: 2
updates:
  - package-ecosystem: cargo
    directory: "/sentrypeer_rust"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: main
  - package-ecosystem: npm
    directory: "/web-gui-theme"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: main
    labels:
      - "dependencies"
      - "npm"