# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only
# Copyright (c) 2021 - 2025 Gavin Henry <ghenry@sentrypeer.org>

name: Cargo Clippy
on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '0 9 * * *' # Daily at 10:00 UTC
  workflow_dispatch:

jobs:
  check:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: Add Homebrew to $PATH
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - name: Test brew call
        run: brew search hello
      - uses: actions/checkout@v2
      - name: Fetch Dependencies
        run: |
          set -x
          sudo apt-get update
          sudo apt-get -y install \
            git \
            build-essential \
            autoconf-archive \
            curl \
            wget \
            libosip2-dev \
            libcmocka-dev \
            uuid-dev \
            libmicrohttpd-dev \
            libjansson-dev \
            libpcre2-dev \
            libsqlite3-dev \
            libcurl4-openssl-dev
            brew update
            brew upgrade          
            brew install libosip opendht
      - name: Run bootstrap.sh
        run: ./bootstrap.sh

      - name: Configure
        run: ./configure

      - name: Build
        run: |
          set -x
          ./bootstrap.sh
          ./configure
          make

      - name: Run Clippy
        run: cd sentrypeer_rust && cargo clippy --all-targets --all-features -- -D warnings