# Found this at https://github.com/maxmind/libmaxminddb/blob/main/.github/workflows/clang-analyzer.yml
# See what it finds...
name: Clang Static Analysis
on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '0 9 * * *' # Daily at 10:00 UTC
jobs:
  clang-analyzer:
    name: Clang static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get install \
          libosip2-dev \
          clang-tools \
          libcmocka-dev \
          uuid-dev \
          libmicrohttpd-dev \
          libjansson-dev \
          libcurl4-openssl-dev
          sudo add-apt-repository ppa:savoury1/utilities
          sudo apt-get update
          sudo apt-get install libmicrohttpd-dev
      - run: |
          set -x
          ./bootstrap.sh
          scan-build ./configure
          scan-build --status-bugs make