# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only
# Copyright (c) 2021 - 2024 Gavin Henry <ghenry@sentrypeer.org>

name: CMake Build and Test
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  test-cmake:
    name: CMake build on ${{matrix.os}} using ${{matrix.cc}} ${{matrix.posix}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04, macos-14]
        cc: [ gcc, clang ]
    env:
      CC: ${{ matrix.cc }}
    steps:
      - name: Add Homebrew to $PATH
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

      - name: Test brew call
        run: brew search hello
      - uses: actions/checkout@v2
      - name: Fetch Dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            set -x
            sudo apt-get update
            sudo echo RESET grub-efi/install_devices | sudo debconf-communicate grub-pc
            sudo apt-get -y upgrade
            rustup update stable
            sudo apt-get install \
            pkg-config \
            autoconf-archive \
            libosip2-dev \
            libcmocka-dev \
            uuid-dev \
            libmicrohttpd-dev \
            libjansson-dev \
            libcurl4-openssl-dev \
            libpcre2-dev \
            libsqlite3-dev \
            libclang-dev -y
            brew update
            brew upgrade
            brew install cmocka libosip opendht
          fi
          if [ "$RUNNER_OS" == "macOS" ]; then
            set -x
            brew update
            brew upgrade || true
            brew install pkg-config
            brew install automake
            brew install autoconf-archive
            brew install libosip
            brew install jansson
            brew install libmicrohttpd
            brew install curl
            brew install cmocka
            brew install pcre2
            brew install opendht
            brew install ossp-uuid
            brew install llvm
            brew install libtool
            echo 'LDFLAGS="-L/opt/homebrew/lib"' >> $GITHUB_ENV
            echo 'CPPFLAGS="-I/opt/homebrew/include"' >> $GITHUB_ENV
          fi
      - name: Build and Clean
        run: |
          set -x
          cmake -S . -B build -DUNIT_TESTING=ON
          cmake --build build
          ctest --test-dir build

