# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only
# Copyright (c) 2021 - 2024 Gavin Henry <ghenry@sentrypeer.org>

name: Cppcheck Static Analysis
on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '0 9 * * *' # Daily at 10:00 UTC
  workflow_dispatch:

jobs:
  clang-analyzer:
    name: Cppcheck Static Analysis
    runs-on: ubuntu-22.04
    steps:
      - name: Add Homebrew to $PATH
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

      - name: Test brew call
        run: brew search hello

      - uses: actions/checkout@v2
      # The only thing really needed is cppcheck, but I'm installing everything anyway
      - run: |
          sudo apt-get update
          sudo apt-get install \
          autoconf-archive \
          libosip2-dev \
          clang-tools \
          libcmocka-dev \
          uuid-dev \
          libmicrohttpd-dev \
          libjansson-dev \
          libpcre2-dev \
          libcurl4-openssl-dev \
          cppcheck -y
          brew update
          brew upgrade          
          brew install libosip opendht
      - run: |
          set -x
          cppcheck --inline-suppr --enable=warning,performance,portability,style --error-exitcode=1 src/
          cppcheck --inline-suppr --enable=warning,performance,portability,style --error-exitcode=1 tests/