# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only
# Copyright (c) 2021 Gavin Henry <ghenry@sentrypeer.org>

name: build_and_test
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Fetch Dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            set -x
            sudo apt-get update
            sudo apt-get -y upgrade
            sudo apt-get install libosip2-dev
          fi
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install automake
            brew install libosip
          fi
      - name: Build and Clean
        run: |
          set -x
          ./bootstrap.sh
          ./configure
          make
          make check
          make distcheck
          ./sentrypeer -V
          make clean