# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only
# Copyright (c) 2021 Gavin Henry <ghenry@sentrypeer.org>

name: Build and Test
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build_and_test:
    name: Autotools build on ${{matrix.os}} using ${{matrix.cc}} ${{matrix.posix}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        cc: [gcc, clang]
    env:
      CC: ${{ matrix.cc }}
    steps:
      - uses: actions/checkout@v2
      - name: Fetch Dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            set -x
            sudo apt-get update
            sudo apt-get -y upgrade
            sudo apt-get install \
            libosip2-dev \
            libcmocka-dev \
            uuid-dev \
            libjansson-dev \
            libcurl4-openssl-dev
            brew install libmicrohttpd
          fi
          if [ "$RUNNER_OS" == "macOS" ]; then
            set -x
            brew install automake
            brew install libosip
            brew install jansson
            brew install libmicrohttpd
            brew install curl
            brew install cmocka
          fi
      - name: Build and Clean
        run: |
          set -x
          ./bootstrap.sh
          ./configure
          make
          make check
          make distcheck
          ./sentrypeer -V
          make clean

# TODO: cmake
# https://github.com/maxmind/libmaxminddb/blob/main/.github/workflows/test.yml
#  cmake_build_and_test:
#    strategy:
#      matrix:
#        os: [ubuntu-latest, macos-latest]
#    name: CMake build on ${{matrix.os}}
#    runs-on: ${{ matrix.os }}
#    steps:
#      - uses: actions/checkout@v2
#      - run: cmake -DBUILD_TESTING=ON .
#      - run: cmake --build .
#      - run: ctest -V .