name: build_and_test
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch Dependencies
        run: |
          set -x
          sudo apt-get update
          sudo apt-get -y install \
            git \
            build-essential
      - name: Build and Clean
        run: |
          set -x
          ./bootstrap.sh
          ./configure
          make
          make check
          make distcheck
          make clean